### PR TITLE
Update SignalR extension version to 1.5.0

### PR DESCRIPTION
**Pull request by Y-Sindo**

### CODE REVIEW

**Review by zackliu — APPROVED** [review]

**Comment by jamiebeachMLI2020** [comment]
Update of summary page with words for all categories
image

**Comment by jamiebeachMLI2020** [comment]
Update to footer Northstar in Summary. Removed potentially ambiguous terms and refined Data to include data protection and data management.

Also you will see an update to the footer to include relevant links - especially our github repo link.
image

**Comment by jamiebeachMLI2020** [comment]
Added details about the Meta Model. (this is couresy of Sandesh)
image

**Comment by jamiebeachMLI2020** [comment]
Initial content for 10k view
image

**Comment by jamiebeachMLI2020** [comment]
Initial content for 10k view
image

**Comment by jamiebeachMLI2020** [comment]
Filled out the Technical Roadmap page a little more.
image

**Pull request merged**
